name: Cypress e2e tests

on:
  push:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
          start: npm run serve
          wait-on: http://localhost:8080/
          config_file: cypress.json
          spec: "tests/e2e/**/*"
          browser: chrome
          env: failOnSnapshotDiff=false # temp solution
      env:
          CYPRESS_baseUrl: http://localhost:8080
    - name: Upload failure screenshots
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: cypress-screenshots
        path: tests/e2e/screenshots
    - name: Upload image diffs
      uses: actions/upload-artifact@v2
      with:
        name: imagediffs
        path: tests/e2e/snapshots/**/__diff_output__/*.png
